project:
  type: website
  output-dir: docs

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on_Exercise"
        menu:
          - text: "Hands-on_Exercise01"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Exercise01.html"
          - text: "Hands-on_Exercise02"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Exercise02.html"
          - text: "Hands-on_Exercise03"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Exercise03.html"  
          - text: "Hands-on_Exercise04"
            href: "Hands-on_Ex/Hands-on_EX04/Hands-on_Exercise04.html"
          - text: "Hands-on_Exercise05"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Exercise05.html"
          - text: "Hands-on_Exercise07"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Exercise07.html"
          - text: "Hands-on_Exercise08"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Exercise08.html"  
          - text: "Hands-on_Exercise09"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Exercise09.html"  
          - text: "Hands-on_Exercise10"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Exercise10.html" 
            
      - text: "Take-home_Exercise"
        menu:
          - text: "Take-home_Exercise01"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Exercise01.html"
          - text: "Take-home_Exercise02"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Exercise02.html"
            
      - text: "Project"
        menu:
          - text: "Proposal"
            href: "Project/proposal.html"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About


format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

